### ISSUE TITLE
Shader documentation

### ISSUE THREAD

**Issue by joshblum** [bastibe/WebGL-Spectrogram#4]
Can a bit of documentation be provided for the shader logic? Specifically I'm interested in the logical behind some of the constants in `physicalColor` of `main.html` and how I could modify them if I wanted.

**Comment by bastibe** [comment]
The physical color scaling is partitioning the full 0...1  range into seven evenly spaced sub-ranges. That's what the modulo and floor are doing. Then, each range modifies only one color channel while keeping the other two constant. This is done in such a way that no two different values map to the same color.

The ranges are:
1. black (0,0,0) to red (1,0,0)
2. red (1,0,0) to yellow (1,1,0)
3. yellow (1,1,0) to green (0,1,0)
4. green (0,1,0) to cyan (0,1,1)
5. cyan (0,1,1) to blue (0,0,1)
6. blue (0,0,1) to magenta (1,0,1)
7. magenta (1,0,1) to white (1,1,1)
